# Generated by Django 4.1.5 on 2023-01-12 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="dystans",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("dystans", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="klient",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nazwa", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
                ("telefon", models.CharField(max_length=9)),
                ("adres", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="wydarzenie",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nazwa", models.CharField(max_length=45)),
                ("miasto", models.CharField(max_length=45)),
                ("termin", models.DateField(max_length=45)),
                (
                    "organizator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zapisy.klient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="zawodnik",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("imie", models.CharField(max_length=45)),
                ("nazwisko", models.CharField(max_length=45)),
                ("klub", models.CharField(max_length=45)),
                ("telefon", models.CharField(max_length=9)),
                ("email", models.CharField(max_length=45)),
                ("miasto", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="zapisy",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("dystans", models.CharField(max_length=45)),
                (
                    "id_zawodnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zapisy.zawodnik",
                    ),
                ),
                (
                    "zawody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zapisy.wydarzenie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="wyniki",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("dystans", models.CharField(max_length=45)),
                ("czas", models.CharField(max_length=45)),
                ("miejsce_open", models.CharField(max_length=45)),
                (
                    "zawodnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zapisy.zawodnik",
                    ),
                ),
                (
                    "zawody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zapisy.wydarzenie",
                    ),
                ),
            ],
        ),
    ]
