# Generated by Django 4.1.2 on 2022-11-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('zawody', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('organizator', models.IntegerField()),
                ('miasto', models.CharField(max_length=45)),
                ('termin', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='wyniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zawodnik', models.IntegerField()),
                ('zawody', models.IntegerField()),
                ('dystans', models.CharField(max_length=45)),
                ('czas', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='zapisy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zawodnik', models.IntegerField()),
                ('zawody', models.IntegerField()),
                ('dystans', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='zawodnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('telefon', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=45)),
                ('miasto', models.CharField(max_length=45)),
            ],
        ),
    ]
