# Generated by Django 4.1.2 on 2022-12-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0002_remove_klient_zawody_alter_wydarzenie_organizator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='adres',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klient',
            name='telefon',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
