# Generated by Django 4.1.2 on 2022-12-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0004_zawodnik_klub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydarzenie',
            name='termin',
            field=models.DateField(max_length=45),
        ),
    ]
