# Generated by Django 4.1.2 on 2022-12-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0005_alter_wydarzenie_termin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyniki',
            name='miejsce_open',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
