# Generated by Django 4.1.2 on 2022-12-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0006_wyniki_miejsce_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='dystans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dystans', models.CharField(max_length=45)),
            ],
        ),
    ]
